[global]
developmentMode = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4CA1A3"
backgroundColor = "#F3F6F8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#273548"
font = "sans serif"
